package drools.rules
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.math.BigDecimal
import com.zhilingsd.asset.manage.decisionengine.common.bo.DroolsResult;
import com.zhilingsd.asset.manage.decisionengine.common.bo.BillVariateBo;

    rule "name1"
    activation-group "group"
        when
            $b:BillVariateBo(            (overdueMoney > 500 || generalCredit <= 50000) &&             (overdueDays > 18)            )
            $d:DroolsResult()
        then
            $d.setQueueNumber("逾期天使大于18");
            $d.setBillTag("逾期天数较长");
        end

    rule "name2"
    activation-group "group"
        when
            $b:BillVariateBo(            (overdueMoney > 500 || generalCredit <= 50000) &&             (overdueDays <= 18)            )
            $d:DroolsResult()
        then
            $d.setQueueNumber("逾期天数小于18");
            $d.setBillTag("逾期天数较短");
        end

    rule "name3"
    activation-group "group"
        when
            $b:BillVariateBo(            (overdueMoney <= 500 && generalCredit > 50000)            )
            $d:DroolsResult()
        then
            $d.setQueueNumber("逾期天数小于500");
            $d.setBillTag("小金额");
        end

