package drools.rules.rulesHello
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.math.BigDecimal
import com.zhilingsd.asset.manage.decisionengine.common.bo.DroolsResult;
import com.zhilingsd.asset.manage.decisionengine.common.bo.BillVariateBo;

    rule "name1"
    activation-group "group"
        when
            $b:BillVariateBo(            (("20" memberOf tag && "23" memberOf tag))            )
            $d:DroolsResult()
        then
            $d.setQueueNumber("DL001");
            $d.setBillTag("小额贷款");
        end

    rule "name2"
    activation-group "group"
        when
            $b:BillVariateBo(            (("20" not memberOf tag  ||  "23" not memberOf tag)) &&             ("13" not memberOf tag || "23" not memberOf tag)            )
            $d:DroolsResult()
        then
            $d.setQueueNumber("feisusong");
            $d.setBillTag("feisusong");
        end

    rule "name3"
    activation-group "group"
        when
            $b:BillVariateBo(            (("20" not memberOf tag  ||  "23" not memberOf tag)) &&             ("13" memberOf tag && "23" memberOf tag)            )
            $d:DroolsResult()
        then
            $d.setQueueNumber("susong");
            $d.setBillTag("susong");
        end

